<?php
require __DIR__.'/../../config/database.php'; require __DIR__.'/../../config/helpers.php';
if (!isset($_SESSION['ID_USER'])) { header('Location: /index.php'); exit; }
requireRole(0);
$labAtual = max(1, min(4, (int)($_GET['lab'] ?? 1)));
$s = $con->prepare('SELECT ID_OCORR, ID_MAQ, titulo, tipo_problema, status_ocorrencia FROM Ocorrencias WHERE ID_LAB = ? ORDER BY ID_OCORR DESC');
$s->bind_param('i', $labAtual); $s->execute(); $ocorrencias = $s->get_result()->fetch_all(MYSQLI_ASSOC); $s->close();
$maquinas = listarMaquinasDoLab($con, $labAtual);
$esquerda = []; $direita = []; foreach ($maquinas as $idx => $maq) { if (($idx % 8) < 4) { $esquerda[] = $maq; } else { $direita[] = $maq; } }
function pcCard(array $m, int $labAtual): void { $info = statusInfo((int)($m['status_maquina'] ?? 0)); $inner = '<span class="pc-number">Baia '.($m['numero'] !== null ? (int)$m['numero'] : '—').'</span><span class="pc-id">#'.(int)$m['ID_MAQ'].'</span><span class="pc-status">'.htmlspecialchars($info['label']).'</span>'; echo '<a class="pc-card '.htmlspecialchars($info['class']).'" href="/suporte/maquinas.php?lab='.$labAtual.'&maquina='.(int)$m['ID_MAQ'].'">'.$inner.'</a>'; }
?><!doctype html><html lang="pt-br"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>BetterOrganized — Laboratório <?=$labAtual?></title><link rel="stylesheet" href="/assets/css/base.css"><link rel="stylesheet" href="/assets/css/painel.css"></head><body><div class="app-shell"><?php renderTopbar('suporte','inicio'); ?><main class="app-main"><div class="lab-page"><div class="lab-toolbar"><label for="lab-select">Laboratório</label><select id="lab-select" onchange="location.href='?lab='+this.value"><?php for($i=1;$i<=4;$i++):?><option value="<?=$i?>" <?=$i===$labAtual?'selected':''?>>Laboratório <?=$i?></option><?php endfor;?></select><a class="btn btn-accent" href="/suporte/relatorio.php?lab=<?=$labAtual?>">+ Novo relatório</a><a class="btn btn-ghost" href="/suporte/relatorio_geral.php?lab=<?=$labAtual?>">Ver relatório / PDF</a></div><ul class="lab-legend"><li><span class="status-dot is-ok"></span>Funcionando</li><li><span class="status-dot is-error"></span>Com defeito</li><li><span class="status-dot is-warn"></span>Manutenção</li></ul><div class="lab-columns"><section class="lab-room"><div class="lab-room-header"><div><h1>Máquinas e baias</h1><p>Visão da sala do Laboratório <?=$labAtual?></p></div><a class="btn btn-ghost" href="/suporte/maquinas.php?lab=<?=$labAtual?>">Ver todas / Cadastrar</a></div><div class="lab-screen">TELA</div><div class="lab-seating"><div class="lab-side"><?php foreach($esquerda as $m) pcCard($m, $labAtual); ?></div><div class="lab-aisle" aria-label="Corredor central"></div><div class="lab-side"><?php foreach($direita as $m) pcCard($m, $labAtual); ?></div><?php if (!$maquinas): ?><p class="lab-empty">Nenhuma máquina cadastrada neste laboratório.</p><?php endif; ?></div></section><aside class="lab-occurrences"><h2>Ocorrências</h2><p>Registros deste laboratório</p><div class="occurrence-stack"><?php if (!$ocorrencias): ?><div class="occurrence-card">Nenhuma ocorrência registrada.</div><?php endif; ?><?php foreach($ocorrencias as $o): $info=statusInfo((int)$o['status_ocorrencia']); ?><div class="occurrence-card"><form action="/suporte/ocorrencia_detalhes.php" method="post"><input type="hidden" name="id_ocorrencia" value="<?=$o['ID_OCORR']?>"><button type="submit" name="submit_button"><span class="occurrence-heading"><span class="status-dot <?=$info['class']?>"></span><strong><?=htmlspecialchars($o['titulo'])?></strong></span><span class="occurrence-details"><?=htmlspecialchars($o['tipo_problema'])?> · Máquina <?= $o['ID_MAQ'] ? '#'.(int)$o['ID_MAQ'] : 'não especificada' ?></span></button></form></div><?php endforeach; ?></div></aside></div></div></main></div></body></html>
